namespace MonitoringXS.Core.Models;

public sealed record NetworkEventBatch(
    IReadOnlyList<NetworkTrafficEvent> Events,
    MetricAvailability Availability,
    NetworkAvailabilityReason Reason,
    long EtwEventsLost,
    long QueueEventsDropped,
    long UnattributedEvents,
    string? Detail = null,
    long EventsObserved = 0,
    int CurrentQueueDepth = 0,
    int MaximumQueueDepth = 0,
    int EtwBufferSizeMegabytes = 0,
    IReadOnlyDictionary<int, int>? ActiveTcpConnectionsByProcess = null,
    IReadOnlyDictionary<int, int>? UdpEndpointsByProcess = null,
    long SendEvents = 0,
    long ReceiveEvents = 0,
    long TcpSendEvents = 0,
    long TcpReceiveEvents = 0,
    long UdpSendEvents = 0,
    long UdpReceiveEvents = 0,
    long IPv4Events = 0,
    long IPv6Events = 0,
    ulong TotalSourceSendBytes = 0,
    ulong TotalSourceReceiveBytes = 0,
    long SystemProcessEvents = 0,
    long UnknownProcessEvents = 0,
    long MetadataLookupFailures = 0,
    long SessionStartFailures = 0,
    long AccessDeniedFailures = 0,
    long EventProcessingFailures = 0,
    long UnsupportedEventVersions = 0,
    int QueueCapacity = 0,
    DateTimeOffset? LastSuccessfulEventTimestampUtc = null,
    MetricAvailability CollectorStatus = MetricAvailability.WarmingUp);
