<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MonitoringXS.Core\MonitoringXS.Core.csproj" />
    <ProjectReference Include="..\..\src\MonitoringXS.Platform.Windows\MonitoringXS.Platform.Windows.csproj" />
    <ProjectReference Include="..\..\src\MonitoringXS.PrivilegedBroker\MonitoringXS.PrivilegedBroker.csproj" />
    <ProjectReference
      Include="..\MonitoringXS.ProcessActionTestHelper\MonitoringXS.ProcessActionTestHelper.csproj"
      AdditionalProperties="Configuration=$(Configuration)"
      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
